import { eq } from 'drizzle-orm';
import { cloudinaryConfigured } from '../../config/env.js';
import { db } from '../../db/index.js';
import { customers } from '../../db/schema.js';
import { audit, type AuditActor } from '../../lib/audit.js';
import { uploadPdf } from '../../lib/cloudinary.js';
import { renderPdf, type PdfDocumentInput } from '../../lib/pdf.js';
import { formatDate } from '../../lib/billing-math.js';
import { lineTotals } from '../../lib/totals.js';
import { ApiError } from '../../utils/api-error.js';
import { getInvoice } from '../invoices/invoices.service.js';
import { loadQuotation } from '../quotations/quotations.repo.js';

/**
 * Server-rendered quotation and invoice PDFs.
 *
 * Each endpoint renders the document, uploads it to Cloudinary, and returns the hosted
 * URL for the frontend to link or embed. When Cloudinary is not configured the same
 * endpoint streams the PDF back directly instead — the document is the deliverable,
 * and a missing third-party account should not remove the feature.
 *
 * The PDF is generated fresh on every request rather than cached. A quotation's terms
 * change during negotiation, and serving a stale document that a customer then treats
 * as the offer is a far worse failure than the cost of re-rendering a few kilobytes.
 *
 * Neither document shows `costPrice` or any margin figure. A quotation PDF is sent to
 * customers, so it is built from the same customer-safe fields the portal uses.
 */

export type DocumentResult =
  | { hosted: true; url: string; publicId: string; bytes: number; reference: string }
  | { hosted: false; buffer: Buffer; filename: string; reference: string };

/**
 * `stream: true` skips the CDN and sends the bytes back, whatever the hosting config.
 *
 * The hosted branch depends on a third-party account staying correctly configured, and
 * when it silently stops delivering (see `canDeliver` in lib/cloudinary) the client is
 * handed a URL that 401s with nothing it can do about it. This is the escape hatch: a
 * client that finds a hosted link undeliverable re-requests with `?stream=1` and gets
 * the document. The bytes are always available — they are rendered on every request —
 * so this can never fail for a reason the hosted path would have avoided.
 */
export type DocumentOptions = { stream?: boolean };

/** Renders a quotation. Customer-facing: no costs, no margins, no risk data. */
export async function quotationPdf(
  actor: AuditActor,
  quotationId: string,
  options: DocumentOptions = {},
): Promise<DocumentResult> {
  const loaded = await loadQuotation(quotationId);

  if (loaded.lines.length === 0) {
    throw ApiError.conflict('EMPTY_QUOTATION', 'This quotation has no lines to render.');
  }

  const meta: { label: string; value: string }[] = [
    { label: 'Issued', value: formatDate(loaded.createdAt) },
  ];
  if (loaded.validUntil) meta.push({ label: 'Valid until', value: loaded.validUntil });
  if (loaded.promisedDeliveryDate) {
    meta.push({ label: 'Delivery by', value: loaded.promisedDeliveryDate });
  }

  const input: PdfDocumentInput = {
    kind: 'Quotation',
    reference: loaded.reference,
    issuedOn: formatDate(loaded.createdAt),
    currency: loaded.currency,
    customerName: loaded.customerName,
    customerContact: loaded.customerContactName,
    customerEmail: loaded.customerEmail,
    meta,
    lines: loaded.lines.map((line) => {
      const totals = lineTotals(line, loaded.orderDiscountPct);
      return {
        productName: line.productName,
        qty: line.qty,
        unitPrice: line.unitPrice,
        discountPct: totals.effectiveDiscountPct,
        total: totals.net,
      };
    }),
    totals: [
      { label: 'Subtotal', value: loaded.totals.subtotal },
      { label: 'You save', value: loaded.totals.savings },
      { label: 'Tax', value: loaded.totals.tax },
      { label: 'Total', value: loaded.totals.grandTotal, strong: true },
    ],
    terms: loaded.customerTerms,
    footNote: 'Generated by DealFlow360. This document is not a tax invoice.',
  };

  return finish(actor, input, `quotations/${loaded.reference}`, 'quotation', quotationId, options);
}

/** Renders an invoice. One-time lines only — recurring charges bill on their own schedule. */
export async function invoicePdf(
  actor: AuditActor,
  invoiceId: string,
  options: DocumentOptions = {},
): Promise<DocumentResult> {
  const invoice = await getInvoice(invoiceId);

  const [customer] = await db
    .select()
    .from(customers)
    .where(eq(customers.id, invoice.customerId))
    .limit(1);

  if (!customer) throw ApiError.notFound('Customer not found');

  const meta: { label: string; value: string }[] = [
    { label: 'Order', value: invoice.quotationReference },
  ];
  if (invoice.issueDate) meta.push({ label: 'Issued', value: invoice.issueDate });
  if (invoice.dueDate) meta.push({ label: 'Due', value: invoice.dueDate });

  const totals = [
    { label: 'Subtotal', value: invoice.subtotal },
    { label: 'Tax', value: invoice.tax },
    { label: 'Total', value: invoice.total, strong: true },
  ];

  // Only shown once money has arrived — a fresh invoice reading "Paid 0.00" is noise.
  if (invoice.amountPaid > 0) {
    totals.push({ label: 'Paid', value: invoice.amountPaid });
    totals.push({ label: 'Balance due', value: invoice.balanceRemaining, strong: true });
  }

  const input: PdfDocumentInput = {
    kind: 'Invoice',
    reference: invoice.reference,
    issuedOn: invoice.issueDate ?? formatDate(new Date()),
    currency: invoice.currency,
    customerName: customer.name,
    customerContact: customer.contactName,
    customerEmail: customer.email,
    meta,
    lines: invoice.lines.map((line) => ({
      productName: line.productName,
      qty: line.qty,
      unitPrice: line.unitPrice,
      discountPct: line.discountPct,
      total: line.total,
    })),
    totals,
    terms: null,
    footNote:
      invoice.balanceRemaining > 0
        ? `Please quote ${invoice.reference} with your payment.`
        : 'Paid in full — thank you.',
  };

  return finish(actor, input, `invoices/${invoice.reference}`, 'invoice', invoiceId, options);
}

async function finish(
  actor: AuditActor,
  input: PdfDocumentInput,
  publicId: string,
  entityType: 'quotation' | 'invoice',
  entityId: string,
  options: DocumentOptions = {},
): Promise<DocumentResult> {
  const buffer = await renderPdf(input);

  if (cloudinaryConfigured && !options.stream) {
    const uploaded = await uploadPdf(buffer, publicId);

    if (uploaded) {
      await audit({
        entityType,
        entityId,
        entityRef: input.reference,
        action: `${input.kind} PDF generated`,
        actor,
        meta: { url: uploaded.url, bytes: uploaded.bytes },
      });

      return {
        hosted: true,
        url: uploaded.url,
        publicId: uploaded.publicId,
        bytes: uploaded.bytes,
        reference: input.reference,
      };
    }
  }

  // Cloudinary absent or the upload failed — hand the bytes straight back.
  await audit({
    entityType,
    entityId,
    entityRef: input.reference,
    action: `${input.kind} PDF generated (streamed)`,
    actor,
    meta: { bytes: buffer.byteLength, hosted: false },
  });

  return {
    hosted: false,
    buffer,
    filename: `${input.reference}.pdf`,
    reference: input.reference,
  };
}
